import type { FinanceState } from './types';

export const categories = ['Food', 'Travel', 'Home', 'Groceries', 'Tickets', 'Other'];

export const initialState: FinanceState = {
  currentUserId: 'm-ivan',
  members: [
    { id: 'm-ivan', name: 'Ivan', username: '@ivan', avatar: 'IT' },
    { id: 'm-anna', name: 'Anna', username: '@anna', avatar: 'AN' },
    { id: 'm-maks', name: 'Maks', username: '@maks', avatar: 'MK' },
    { id: 'm-lena', name: 'Lena', username: '@lena', avatar: 'LN' },
    { id: 'm-dima', name: 'Dima', username: '@dima', avatar: 'DM' },
  ],
  groups: [
    {
      id: 'g-trip',
      title: 'Istanbul Trip',
      subtitle: 'Flights, dinners and city rides',
      currency: 'USD',
      imageName: 'finance-trip.png',
      memberIds: ['m-ivan', 'm-anna', 'm-maks', 'm-lena'],
      color: '#0e8f7f',
    },
    {
      id: 'g-dinner',
      title: 'Friday Dinner',
      subtitle: 'Shared table, wine and taxi',
      currency: 'USD',
      imageName: 'finance-cover.png',
      memberIds: ['m-ivan', 'm-anna', 'm-dima'],
      color: '#916a24',
    },
    {
      id: 'g-flat',
      title: 'Apartment 12B',
      subtitle: 'Rent, utilities and groceries',
      currency: 'USD',
      imageName: 'finance-balance.png',
      memberIds: ['m-ivan', 'm-maks', 'm-lena', 'm-dima'],
      color: '#596db6',
    },
  ],
  expenses: [
    {
      id: 'e-1',
      groupId: 'g-trip',
      title: 'Airport transfer',
      category: 'Travel',
      amountCents: 7600,
      paidBy: 'm-ivan',
      splitMode: 'equal',
      splitParticipants: ['m-ivan', 'm-anna', 'm-maks', 'm-lena'],
      paidAt: '2026-07-03T10:20:00.000Z',
    },
    {
      id: 'e-2',
      groupId: 'g-trip',
      title: 'Dinner near Galata',
      category: 'Food',
      amountCents: 12840,
      paidBy: 'm-anna',
      splitMode: 'manual',
      splitParticipants: ['m-ivan', 'm-anna', 'm-maks', 'm-lena'],
      manualSplits: {
        'm-ivan': 3200,
        'm-anna': 2840,
        'm-maks': 3400,
        'm-lena': 3400,
      },
      paidAt: '2026-07-04T19:10:00.000Z',
    },
    {
      id: 'e-3',
      groupId: 'g-trip',
      title: 'Museum tickets',
      category: 'Tickets',
      amountCents: 9000,
      paidBy: 'm-lena',
      splitMode: 'equal',
      splitParticipants: ['m-ivan', 'm-anna', 'm-maks'],
      paidAt: '2026-07-05T14:30:00.000Z',
    },
    {
      id: 'e-4',
      groupId: 'g-dinner',
      title: 'Shared dinner bill',
      category: 'Food',
      amountCents: 15420,
      paidBy: 'm-dima',
      splitMode: 'equal',
      splitParticipants: ['m-ivan', 'm-anna', 'm-dima'],
      paidAt: '2026-07-02T20:15:00.000Z',
    },
    {
      id: 'e-5',
      groupId: 'g-dinner',
      title: 'Taxi home',
      category: 'Travel',
      amountCents: 3810,
      paidBy: 'm-ivan',
      splitMode: 'manual',
      splitParticipants: ['m-ivan', 'm-anna', 'm-dima'],
      manualSplits: {
        'm-ivan': 1270,
        'm-anna': 1270,
        'm-dima': 1270,
      },
      paidAt: '2026-07-02T23:45:00.000Z',
    },
    {
      id: 'e-6',
      groupId: 'g-flat',
      title: 'July rent',
      category: 'Home',
      amountCents: 120000,
      paidBy: 'm-maks',
      splitMode: 'equal',
      splitParticipants: ['m-ivan', 'm-maks', 'm-lena', 'm-dima'],
      paidAt: '2026-07-01T09:00:00.000Z',
    },
    {
      id: 'e-7',
      groupId: 'g-flat',
      title: 'Groceries for week',
      category: 'Groceries',
      amountCents: 23870,
      paidBy: 'm-lena',
      splitMode: 'manual',
      splitParticipants: ['m-ivan', 'm-maks', 'm-lena', 'm-dima'],
      manualSplits: {
        'm-ivan': 5700,
        'm-maks': 6100,
        'm-lena': 5870,
        'm-dima': 6200,
      },
      paidAt: '2026-07-06T18:20:00.000Z',
    },
  ],
  settlements: [
    {
      id: 's-1',
      groupId: 'g-dinner',
      fromId: 'm-anna',
      toId: 'm-dima',
      amountCents: 2500,
      status: 'confirmed',
      createdAt: '2026-07-03T09:30:00.000Z',
    },
  ],
};
